2018-06-20 08:03:39,135 - ERROR - 22 - __main__ - logging_py - exception occurs
NoneType: None
